export const ApiRoutes = {
  bootstrap: '/app/bootstrap',
  wechatLogin: '/auth/wechat-login',
  authSession: '/auth/session',
  logout: '/auth/logout',
  lobbySummary: '/lobby/summary',
  rooms: '/rooms',
  joinRoom: (roomId: string) => `/rooms/${roomId}/join`,
  leaveRoom: (roomId: string) => `/rooms/${roomId}/leave`,
  roomPreview: (roomId: string) => `/rooms/${roomId}/preview`,
  addAi: (roomId: string) => `/rooms/${roomId}/add-ai`,
  removeAi: (roomId: string) => `/rooms/${roomId}/remove-ai`,
  roomReady: (roomId: string) => `/rooms/${roomId}/ready`,
  updateRoomRules: (roomId: string) => `/rooms/${roomId}/rules`,
  startGame: (roomId: string) => `/rooms/${roomId}/start`,
  room: (roomId: string) => `/rooms/${roomId}`,
  gameView: (gameId: string) => `/games/${gameId}/view`,
  gameAction: (gameId: string) => `/games/${gameId}/actions`,
  replays: '/replays',
  replay: (gameId: string) => `/replays/${gameId}`,
};
